/**
 * AQ-02B2 — Search Completion.
 *
 * Consumes the search-index artifacts each domain's publication pipeline
 * already generates (data/search/*.json) and turns them into the one
 * client-side asset the homepage search widget imports. This is
 * registry-driven (loops listPublishedDomainIds(), not a fixed domain
 * list) so a newly published domain becomes searchable automatically —
 * no change to assets/js/semantic-entry.js is required per domain, only
 * a rerun of this stage.
 */

import fs from "fs";
import path from "path";
import { getDomainConfig, listPublishedDomainIds } from "../food-domain-config.js";
import { readJson } from "./utils.js";

function buildHaystack(doc, domain, tierLabel) {
  const parts = [
    doc.display_name ?? doc.name,
    domain.entityLabels.leafPlural,
    tierLabel,
    doc.classification?.group?.name,
    doc.classification?.category?.name,
    doc.intrinsic?.scientific_name,
    ...(doc.tokens ?? []),
  ].filter(Boolean);
  return parts.join(" ").toLowerCase();
}

function tierEntries(domain, tier, tierLabel) {
  const searchPath = domain.paths.search[tier];
  if (!fs.existsSync(searchPath)) return [];
  const { documents } = readJson(searchPath);
  return documents.map((doc) => ({
    slug: doc.slug,
    name: doc.display_name ?? doc.name,
    entityType: doc.document_type ?? domain.id,
    classification: `${domain.entityLabels.leafPlural} ${tierLabel}`,
    href: doc.canonical_path,
    haystack: buildHaystack(doc, domain, tierLabel),
  }));
}

/** Every leaf + group + category search document across every published domain, in one flat array. */
export function buildFoodOntologySearchIndex(root) {
  const entries = [];
  for (const id of listPublishedDomainIds()) {
    const domain = getDomainConfig(id, root);
    entries.push(...tierEntries(domain, "leaf", "Ingredient"));
    entries.push(...tierEntries(domain, "group", "Group"));
    entries.push(...tierEntries(domain, "category", "Category"));
  }
  return entries.sort((a, b) => a.slug.localeCompare(b.slug));
}

export function runSearchAssetsStage(root) {
  const entries = buildFoodOntologySearchIndex(root);
  const outFile = path.join(root, "assets", "js", "food-ontology-search-index.js");
  const body = `/**
 * Auto-generated by scripts/generate-food-search-assets.mjs — do not edit.
 * AQ-02B2 — every published food-ontology leaf/group/category entity,
 * consumed by assets/js/semantic-entry.js. Regenerate by rerunning the
 * script; a newly published domain is picked up automatically because
 * this file is built from listPublishedDomainIds(), not a fixed list.
 */
export const FOOD_ONTOLOGY_SEARCH_INDEX = ${JSON.stringify(entries, null, 2)};
`;
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, "utf8");
  return { outFile, entryCount: entries.length };
}
